---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: An analysis of temperature anomalies
draft: false
image: climate.jpg
keywords: ""
slug: climate
title: Climate Change
---



<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>We wanted to study climate change and used data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. And we found the <a href="https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.txt">tabular data of temperature anomalies here</a></p>
<p>We run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>We selected the year and the twelve month variables from the <code>weather</code> dataset and ignored the others (J-D, D-N, DJF, etc.) and converted the dataframe from wide to ‘long’ format using the code below:</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;% 
  select(-14:-19) %&gt;% 
    pivot_longer(cols = 2:13, 
                 names_to = &quot;Month&quot;, 
                 values_to = &quot;delta&quot;
                  )</code></pre>
<p>We inspected our dataframe and it has three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>We plot the data using a time-series scatter plot, and added a trendline to this plot. We first created a new variable called <code>date</code> to plot the <code>delta</code> values chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/projects/climate_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<div id="is-the-effect-of-increasing-temperature-more-pronounced-in-some-months" class="section level3">
<h3>Is the effect of increasing temperature more pronounced in some months?</h3>
<p><strong>Based on our plots below, the effect of increasing temperature does not depend on month since the smoothing lines across months in different years are quite similar in shape and point values.</strong></p>
<pre class="r"><code>ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  facet_wrap(~month) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies by Month&quot;
  )</code></pre>
<p><img src="/projects/climate_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="looking-at-the-data-in-time-intervals" class="section level3">
<h3>Looking at the data in time intervals</h3>
<p>We grouped data into different time periods to study historical data. We chose a time frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We removed data before 1800 using <code>filter</code>. Then, we used the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to and assigned the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we created a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in.</p>
<p><strong>From our plots below, we could see that the most frequent monthly delta values among these time intervals gradually shifted from ~ -0.25 to ~ 0.8, from 1881 - 1920 to 2011 - present, showing the underlying trend of temperature increase across the past centuries.</strong></p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="/projects/climate_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="average-annual-anomalies" class="section level3">
<h3>Average annual anomalies</h3>
<p>So far, we have been working with monthly anomalies. However, we are interested in average annual anomalies. We did this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<p><strong>Unsurprisingly, the average annual anomalies demonstrated the same trend with monthly anomalies across different years since as discussed above, the weather anomalies does not depend on months but on years.</strong></p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/projects/climate_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a></p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>We constructed a confidence interval for the average annual delta since 2011, both using a formula and a bootstrap simulation with the <code>infer</code> package.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  filter(interval == &quot;2011-present&quot;) %&gt;% 
  # what dplyr verb will you use? 
  summarize(mean_delta = mean(delta, na.rm = TRUE), SD_delta = sd(delta, na.rm = TRUE), count_delta = n(), 
            SE_delta = SD_delta/sqrt(count_delta), lower95_delta = mean_delta - qnorm(0.025,0,1)*SE_delta, upper95_delta = mean_delta + qnorm(0.025,0,1)*SE_delta)

formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 6
##   mean_delta SD_delta count_delta SE_delta lower95_delta upper95_delta
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;    &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
## 1      0.966    0.262         108   0.0252          1.02         0.916</code></pre>
<pre class="r"><code># use the infer package to construct a 95% CI for delta

set.seed(1234)
bootstrapped_CI &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;% 
  specify(response = delta) %&gt;%
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)

bootstrapped_CI</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.917     1.02</code></pre>
<p><strong>From these data we could see that the 95% confidence intervals of the mean temperature anomaly calculated from the formula method and the bootstrap simulation are similar, as (~0.916, 1.02). This indicates that we are 95% confident that the average temperature delta is between ~0.916 and 1.02. In the formula method, we carried out our calculation directly on the temperature anomalies data after 2011. While in the bootstrap simulation, we took 1000 bootstrap samples (large enough samples; samples with replacement and same sample size). Since the bootstrap simulation got similar results as using formulas directly, our estimation of the confidence interval should be quite accurate.</strong></p>
</div>
</div>
